# Generated by Django 4.2.8 on 2024-01-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loguser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.EmailField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=50)),
                ('doc', models.FileField(upload_to='')),
                ('inote', models.CharField(max_length=500)),
                ('dates', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.loguser')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=500)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loguser')),
            ],
        ),
    ]
