# Generated by Django 4.2.8 on 2024-01-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
